### ISSUE TITLE
How to add a favicon to the theme?

### ISSUE THREAD

**Issue by mashsaxena** [themefisher/parsa-jekyll#1]
I am unable to add a favicon to my jekyll blog with this theme. Any suggestions?

**Comment by developer-evan** [comment]
Hi @mashsaxena 

Please add an image with the name of `favicon.png` in the images folder. It will automatically sync. thank you

**Comment by developer-evan** [comment]
I am going to close this issue, if you fetch any more issue, please create a new issue or re open this issue. thank you
